"""Generate the density-evaluation LaTeX table from density_evaluation.xlsx.

Usage:
    python gen_density_table.py
    python gen_density_table.py --exclude lag_llama toto
"""

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
from config import PROJECT_ROOT, VOLARE_RESULTS_DIR
from evaluation.density_io import DECILE_ONLY_MODELS

MODELS = {
    "har_logn_gaussian": "HAR-Gaussian",
    "har_logn_empirical": "HAR-Empirical",
    "chronos_bolt_small": "Chronos-Bolt-S",
    "chronos_bolt_base": "Chronos-Bolt-B",
    "timesfm_2_5": "TimesFM 2.5",
    "moirai_2_0_small": "Moirai-2.0-S",
    "moirai_moe_small": "Moirai-MoE-S",
    "sundial": "Sundial",
    "toto": "Toto",
    "lag_llama": "Lag-Llama",
}
HAR = {"har_logn_gaussian", "har_logn_empirical"}

# (column, header, format, significance-test loss key in density_significance.xlsx)
COLUMNS = [
    ("log_crps_mean", "CRPS", "{:.3f}", "crps"),
    ("log_coverage_50", "Cov\\,50\\%", "{:.2f}", None),
    ("log_coverage_80", "Cov\\,80\\%", "{:.2f}", None),
    ("log_coverage_95", "Cov\\,95\\%", "{:.2f}", None),
    ("log_interval_score_80", "IS\\,80\\%", "{:.3f}", "is80"),
    ("log_interval_score_95", "IS\\,95\\%", "{:.3f}", None),
    ("reject_ks_pct", "KS", "{:.0f}", None),
    ("reject_berkowitz_pct", "Berk", "{:.0f}", None),
    ("reject_lb_pct", "LB", "{:.0f}", None),
]
NA = "n/a\\tnote{f}"


def panel(df: pd.DataFrame, h: int, letter: str, mcs: set) -> str:
    sub = df[df["horizon"] == h].set_index("model")
    spec = "l" + "c" * len(COLUMNS)
    head = " & ".join(["Model"] + [hdr for _, hdr, _, _ in COLUMNS])
    lines = [
        f"\\multicolumn{{{len(COLUMNS) + 1}}}{{l}}{{\\textbf{{Panel {letter}: $h = {h}$}}}} \\\\",
    ]
    prev_har = None
    for m in sub.index:
        is_har = m in HAR
        if prev_har is True and not is_har:
            lines.append("\\addlinespace")
        prev_har = is_har
        cells = [MODELS[m]]
        for c, _, fmt, loss in COLUMNS:
            v = sub.at[m, c] if c in sub.columns else np.nan
            if pd.isna(v):
                cells.append(NA if m in DECILE_ONLY_MODELS else "--")
                continue
            s = fmt.format(v)
            if loss and (h, loss, m) in mcs:
                s += "$^{\\dagger}$"
            cells.append(s)
        lines.append(" & ".join(cells) + " \\\\")
    return spec, head, "\n".join(lines)


def build(df: pd.DataFrame, mcs: set) -> str:
    parts = []
    spec = head = None
    for h, letter in ((1, "A"), (5, "B"), (22, "C")):
        spec, head, body = panel(df, h, letter, mcs)
        parts.append(body)
    body = "\n\\midrule\n".join(parts)
    return f"""% Generated by code/gen_density_table.py -- do not edit by hand.
% Requires \\usepackage{{booktabs, threeparttable}}
\\begin{{table}}[htbp]
\\centering
\\begin{{threeparttable}}
\\caption{{Density forecast evaluation: cross-asset means (log-RV scale).}}
\\label{{tab:density-eval}}
\\footnotesize
\\setlength{{\\tabcolsep}}{{4pt}}
\\begin{{tabular}}{{{spec}}}
\\toprule
{head} \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\begin{{tablenotes}}\\footnotesize
\\item[a] CRPS is the continuous ranked probability score (lower is better).
\\item[b] Cov\\,50/80/95\\% is the empirical coverage of the nominal central interval (ideal: 0.50/0.80/0.95).
\\item[c] IS is the interval score at the stated level (lower is better; penalises both width and miscoverage).
\\item[d] KS/Berk/LB are rejection rates (\\%) of the Kolmogorov--Smirnov, Berkowitz and Ljung--Box PIT tests at the 5\\% level across the 40-stock panel. The PIT is drawn uniformly between the two grid levels that bracket the realisation, which is exactly uniform under a correct forecast; for the decile-only models only the nine native levels are used. At $h > 1$ all three tests use every $h$-th PIT value to remove the serial correlation induced by overlapping targets.
\\item[$\\dagger$] Model is in the 90\\% model confidence set (Hansen, Lunde and Nason, 2011) for that loss, computed on the cross-asset average loss per date.
\\item[e] Lag-Llama is excluded as its CPU-only inference is prohibitively slow (${{\\sim}}4\\,500$ CPU-hours for the full panel).
\\item[f] Not available: Chronos-Bolt, TimesFM 2.5 and Moirai-2.0-S emit only native deciles, so their 2.5\\% and 97.5\\% quantiles would be extrapolations rather than model output.
\\end{{tablenotes}}
\\end{{threeparttable}}
\\end{{table}}
"""


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--input", default=str(VOLARE_RESULTS_DIR / "density" / "density_evaluation.xlsx"))
    p.add_argument("--output", default=str(PROJECT_ROOT / "paper" / "tables" / "table_density_eval.tex"))
    p.add_argument("--significance", default=str(VOLARE_RESULTS_DIR / "density" / "density_significance.xlsx"))
    p.add_argument("--exclude", nargs="*", default=["lag_llama"])
    args = p.parse_args()

    df = pd.read_excel(args.input, sheet_name="summary")
    df = df[df["model"].isin(MODELS) & ~df["model"].isin(args.exclude)].copy()
    df["_order"] = df["model"].map({m: i for i, m in enumerate(MODELS)})
    df = df.sort_values(["_order", "horizon"])

    sig = pd.read_excel(args.significance, sheet_name="panel_mcs")
    mcs = set(sig.loc[sig["in_mcs"], ["horizon", "loss", "model"]].itertuples(index=False, name=None))

    Path(args.output).write_text(build(df, mcs))
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
